### PR TITLE
add user - test

### PR DESCRIPTION
**Pull request by cunla**

### CODE REVIEW

**Review by tim-schilling — APPROVED** [review]

**Comment by tim-schilling** [comment]
@cunla I think I found it:

From https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository
>  Note: When used with GitHub App authentication, even GET requests must have the contents:write permission. Without it, the following attributes will be ignored, leading to unexpected behavior and confusing diffs:
> 
> [allow_merge_commit](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#allow_merge_commit) (including the related merge_commit_title and merge_commit_message)
>     [allow_squash_merge](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#allow_squash_merge) (including the related squash_merge_commit_title and squash_merge_commit_message)
>     [allow_rebase_merge](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#allow_rebase_merge)

This is exactly what we're seeing.

**Comment by tim-schilling** [comment]
@cunla alright, I think we need to regenerate the PAT that's being used so it includes the administration permission as per https://github.com/integrations/terraform-provider-github/issues/679#issuecomment-2068196839

When you do that, can you also write something in #22 as a comment (I can document it later) or in the docs on the repo somewhere?

**Comment by cunla** [comment]
Ok, I recreated the token, and first applied some changes locally. Now when I run locally `tf plan` I am getting `No changes. Your infrastructure matches the configuration.`

Looks like it worked.

**Comment by cunla** [comment]
This PR can be closed, this user is mine for test purposes.

**Pull request closed without merging**
