### PR TITLE
Terraform v2

### PR DESCRIPTION
**Pull request by cunla**
Hi,

Following all the comments, as well as a short conversation I had with @tim-schilling, I decided to simplify the terraform code.

The main difference compared to the previous version is: 
Since we have only three repository teams for each repository (repo-team, repo-admins-team and repo-committers-team) - we can define it as part of the repository definition.

So now, looking at two repositories as samples: 
* `controls` does not have the teams structure associated with it (no `controls-admin`/`controls-committers` teams), and it is defined by `skip_team_creation=true`
* `django-commons-playground` has three teams associated with it:
  * `django-commons-playground` with all users from `admins`/`committers`/`members` lists.
  * `django-commons-playground-committers` with all users from `admins`/`committers` lists.
  * `django-commons-playground-admins` with all users from `admins` list.

```terraform
repositories = {
  # ...
  "controls" = {
    description              = "The controls for managing Django Commons projects"
    enable_branch_protection = false

    topics = []
    push_allowances = []
    visibility = "public"
    skip_team_creation = true
  }
  "django-commons-playground" = {
    description = "A sample project to test things out"
    topics = []

    admins = [
      "tim-schilling",
      "williln",
      "ryancheley",
      "Stormheg",
      "cunla",
    ]
    committers = [
      "priyapahwa",
    ]
    members = [ # Add members with triage permissions
    ]
  }
}
```

### CODE REVIEW

**Comment by tim-schilling** [comment]
@cunla did this incorporate all of Lacey's suggestions from the other PR? I think it did, but I haven't gone through it thoroughly.

**Comment by cunla** [comment]
> @cunla did this incorporate all of Lacey's suggestions from the other PR? I think it did, but I haven't gone through it thoroughly.

I think I included everything that was suggested.

**Comment by cunla** [comment]
Are we good with merging this? I would like to merge so I can track what's happening in the `apply` workflow during. I am sure there will be some fixes required there.

**Review by tim-schilling — APPROVED** [review]
I'm good with this. We can revert this and go back to the `new_team.yml` if we want based on our meeting discussion in a few weeks.

**Pull request merged**
